In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of the words",
    "your videos are good"
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of the words',
 'your videos are good']

In [7]:
voc_size=1000

#ONE HOT REPRESENTATION

In [8]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[203, 916, 656, 591], [203, 916, 656, 206], [203, 464, 656, 257], [473, 401, 19, 216, 752], [473, 401, 19, 216, 541], [114, 203, 669, 656, 203, 253], [965, 737, 27, 216]]


# WORD EMBEDDING REPRESENTATION

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 203 916 656 591]
 [  0   0   0   0 203 916 656 206]
 [  0   0   0   0 203 464 656 257]
 [  0   0   0 473 401  19 216 752]
 [  0   0   0 473 401  19 216 541]
 [  0   0 114 203 669 656 203 253]
 [  0   0   0   0 965 737  27 216]]


In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding="post",maxlen=sent_length)
print(embedded_docs)

[[203 916 656 591   0   0   0   0]
 [203 916 656 206   0   0   0   0]
 [203 464 656 257   0   0   0   0]
 [473 401  19 216 752   0   0   0]
 [473 401  19 216 541   0   0   0]
 [114 203 669 656 203 253   0   0]
 [965 737  27 216   0   0   0   0]]


In [16]:
model=Sequential()
model.add(Embedding(voc_size,12,input_length=sent_length))
model.compile("adam","mse")

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 12)             12000     
                                                                 
Total params: 12000 (46.88 KB)
Trainable params: 12000 (46.88 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 42ms/step
[[[-0.02002635 -0.01223564 -0.00368889  0.02625397 -0.01348257
    0.00058775 -0.04950775 -0.03088241 -0.01640389 -0.03511623
   -0.0381655  -0.01887997]
  [-0.00205554  0.03520015 -0.01813617 -0.00210543  0.02223071
   -0.03089446 -0.04661664 -0.02957306  0.04751955  0.03939975
   -0.03902968  0.03121095]
  [-0.0125505   0.03469167 -0.02338131  0.02113973 -0.00499849
    0.03480515  0.03139646  0.04611833 -0.04500139 -0.00479674
    0.04340706  0.00667239]
  [ 0.03706297 -0.03636061 -0.03852759  0.00468011 -0.02796783
    0.02737733  0.04029277  0.01448933  0.00032351  0.04340712
   -0.00816245  0.04026454]
  [-0.00421982  0.0395675  -0.02910757 -0.03169322 -0.0267736
    0.01850494  0.00144779  0.03704405 -0.0175162   0.01168122
   -0.00677619  0.01174288]
  [-0.00421982  0.0395675  -0.02910757 -0.03169322 -0.0267736
    0.01850494  0.00144779  0.03704405 -0.0175162   0.01168122
   -0.00677619  0.01174288]
  [-0.00421982  0.0395675 

In [20]:
embedded_docs[0]

array([203, 916, 656, 591,   0,   0,   0,   0], dtype=int32)